### ISSUE TITLE
When I correct natural abundance,I have a question about result, and I don't know why?

### ISSUE THREAD

**Issue by nyj123** [XiaoyangSu/AccuCor#14]
for example,
this is my raw data
![image](https://user-images.githubusercontent.com/61054316/93453781-afa56f80-f90c-11ea-9bea-bff2e547ad30.png)
and my result like this
![image](https://user-images.githubusercontent.com/61054316/93453925-da8fc380-f90c-11ea-809a-2e2a0f4f52b5.png)
and I don't kmow why lactate m+3 abundance will be more.
I use U-C13glutamine tracer.

Thanks very much!

**Comment by nyj123** [comment]
And I calculate by the formula 
![image](https://user-images.githubusercontent.com/61054316/93454361-791c2480-f90d-11ea-9469-aa09385d90ef.png),
Only m+3,I think it has something wrong

Thanks a lot

**Comment by XiaoyangSu** [comment]
The lactate M+3 goes up after correction is normal. This is because the tracers typically have 99% isotope purity (99% 13C and 1% natural carbon). I assume you are using the 13C5-glutamine from Cambridge Isotope Laboratory (see https://shop.isotope.com/productdetails.aspx?itemno=CLM-1822-H-PK), which is 99% 13C. If your tracer is 100% pure, you can change the tracer purity parameter (purity=1). Please note this is the isotope purity, not chemical purity.
Meanwhile, our correction isn't sequential from M+0 to M+n. We use non-negative least squares regression to correct all the labeled fractions together. Please see our Anal Chem paper for more details.

**Comment by nyj123** [comment]
Oh,I get it! Thanks a lot!
